-- KIP Financial CRM - Zoho-style foundation
create extension if not exists pgcrypto;
create table if not exists public.kip_organizations(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz default now());
create table if not exists public.kip_profiles(id uuid primary key references auth.users(id) on delete cascade,organization_id uuid not null references public.kip_organizations(id) on delete cascade,full_name text,role text default 'Admin',created_at timestamptz default now());
create table if not exists public.kip_records(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.kip_organizations(id) on delete cascade,module text not null,name text not null,owner_id uuid references auth.users(id),status text,source text,amount numeric(14,2) default 0,phone text,email text,company text,notes text,data jsonb default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
create index if not exists kip_records_org_module on public.kip_records(organization_id,module);
create index if not exists kip_records_org_created on public.kip_records(organization_id,created_at desc);
create table if not exists public.kip_activities(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.kip_organizations(id) on delete cascade,record_id uuid references public.kip_records(id) on delete cascade,owner_id uuid references auth.users(id),type text default 'Task',subject text not null,status text default 'Pending',due_at timestamptz,description text,created_at timestamptz default now());
create table if not exists public.kip_settings(id uuid primary key default gen_random_uuid(),organization_id uuid unique not null references public.kip_organizations(id) on delete cascade,lead_statuses jsonb default '["New","Contacted","Qualified","Unqualified","Converted","Lost"]',deal_stages jsonb default '["Qualification","Needs Analysis","Value Proposition","Proposal/Price Quote","Negotiation/Review","Closed Won","Closed Lost"]',lead_sources jsonb default '["Website","Facebook","Google","WhatsApp","Referral","Exhibition","Email","Phone","Other"]',custom_modules jsonb default '[]',custom_fields jsonb default '{}',updated_at timestamptz default now());
create or replace function public.kip_create_org(org_name text,user_name text) returns uuid language plpgsql security definer set search_path=public as $$declare oid uuid;begin if auth.uid() is null then raise exception 'Authentication required';end if;insert into kip_organizations(name) values(trim(org_name)) returning id into oid;insert into kip_profiles(id,organization_id,full_name,role) values(auth.uid(),oid,nullif(trim(user_name),''),'Admin');insert into kip_settings(organization_id) values(oid);return oid;end;$$;
create or replace function public.kip_my_org() returns uuid language sql stable security definer set search_path=public as $$select organization_id from kip_profiles where id=auth.uid() limit 1$$;
alter table public.kip_organizations enable row level security;alter table public.kip_profiles enable row level security;alter table public.kip_records enable row level security;alter table public.kip_activities enable row level security;alter table public.kip_settings enable row level security;
create policy kip_org_select on kip_organizations for select using(id=kip_my_org());
create policy kip_profile_org on kip_profiles for all using(organization_id=kip_my_org()) with check(organization_id=kip_my_org());
create policy kip_records_org on kip_records for all using(organization_id=kip_my_org()) with check(organization_id=kip_my_org());
create policy kip_activities_org on kip_activities for all using(organization_id=kip_my_org()) with check(organization_id=kip_my_org());
create policy kip_settings_org on kip_settings for all using(organization_id=kip_my_org()) with check(organization_id=kip_my_org());
grant execute on function public.kip_create_org(text,text) to authenticated;grant execute on function public.kip_my_org() to authenticated;
